---
- name: Install Docker, deploy SonarQube LTS, and install Trivy
  hosts: jenkins
  become: yes
  vars:
    sonarqube_port: 9000
    postgres_password: sonarpass
    trivy_version: "0.56.2"  # Update this to the latest version as needed

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes
        allow_unauthenticated: yes

    - name: Install required packages for Docker and Trivy
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - wget
        state: present

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add the Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present

    - name: Ensure Docker is started and enabled
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Python module
      pip:
        name: docker

    - name: Create Docker network for SonarQube
      docker_network:
        name: sonarnet

    - name: Run PostgreSQL container
      docker_container:
        name: sonarqube-db
        image: postgres:13
        networks:
          - name: sonarnet
        env:
          POSTGRES_USER: sonar
          POSTGRES_PASSWORD: "{{ postgres_password }}"
        volumes:
          - sonarqube_db:/var/lib/postgresql/data

    - name: Run SonarQube LTS container
      docker_container:
        name: sonarqube
        image: sonarqube:lts
        networks:
          - name: sonarnet
        ports:
          - "{{ sonarqube_port }}:9000"
        env:
          SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db/sonar
          SONAR_JDBC_USERNAME: sonar
          SONAR_JDBC_PASSWORD: "{{ postgres_password }}"
        volumes:
          - sonarqube_data:/opt/sonarqube/data
          - sonarqube_extensions:/opt/sonarqube/extensions
          - sonarqube_logs:/opt/sonarqube/logs
        ulimits:
          nofile:
            soft: 65536
            hard: 65536
        restart_policy: always

    - name: Wait for SonarQube to be ready
      wait_for:
        port: "{{ sonarqube_port }}"
        delay: 30
        timeout: 300

    - name: Download Trivy
      get_url:
        url: "https://github.com/aquasecurity/trivy/releases/download/v{{ trivy_version }}/trivy_{{ trivy_version }}_Linux-64bit.tar.gz"
        dest: /tmp/trivy.tar.gz

    - name: Extract Trivy
      unarchive:
        src: /tmp/trivy.tar.gz
        dest: /usr/local/bin
        remote_src: yes

    - name: Make Trivy executable
      file:
        path: /usr/local/bin/trivy
        mode: '0755'

    - name: Verify Trivy installation
      command: trivy --version
      register: trivy_version_output

    - name: Display Trivy version
      debug:
        var: trivy_version_output.stdout

    - name: Print access information
      debug:
        msg: 
          - "SonarQube is now accessible at http://{{ ansible_host }}:{{ sonarqube_port }}"
          - "Trivy has been installed and is available from the command line"
